#pragma once

#define STELLARLIBS_VER_MAJOR 1
#define STELLARLIBS_VER_MINOR 0
#define STELLARLIBS_VER_PATCH 0

#define STELLARLIBS_VERSION (STELLARLIBS_VER_MAJOR * 10000 + STELLARLIBS_VER_MINOR * 100 + STELLARLIBS_VER_PATCH)