#name: Windows

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

#env:

#jobs:
#  build:
#    runs-on: windows-latest

#    steps:
#      - uses: actions/checkout@v2

# ------------------------ REMOVE --------------------------
#      - uses: actions/cache@v2
#        with:
#          path: "**/cpm_modules"
#          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
# ----------------------------------------------------------

#      - name: configure
#        run: cmake -Stest -Bbuild

#      - name: build
#        run: cmake --build build --config Debug -j4

#      - name: test
#        run: |
#          cd build
#          ctest --build-config Debug